import type { Metadata } from "next"
import "./globals.css"
import { inter, raleway } from "./utils/fonts"

export const metadata: Metadata = {
  title: "Hotel Daifa - Florianópolis",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-br">
      <link rel="icon" href="/favicon.ico" sizes="any" />
      <body className={`${inter} ${raleway} antialiased`}>{children}</body>
    </html>
  )
}
